"""Render a parsed DconfDoc into home-manager compatible Nix source."""

from __future__ import annotations

from .categorize import categorize
from .parser import DconfDoc

HEADER = (
    "# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome\n"
    "# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.\n"
)


def _render_section_block(section: str, kvs: list[tuple[str, str]], indent: str) -> list[str]:
    lines = [f'{indent}"{section}" = {{']
    for key, val in kvs:
        lines.append(f"{indent}  {key} = {val};")
    lines.append(f"{indent}}};")
    return lines


def render_single(doc: DconfDoc, module_header: bool = True) -> str:
    """Render the whole doc as one home-manager module file."""
    out = []
    if module_header:
        out.append(HEADER)
        out.append("{ lib, ... }:")
        out.append("")
    out.append("{")
    out.append("  dconf.settings = {")
    for section in doc.order:
        kvs = doc.sections[section]
        if not kvs:
            continue
        out.extend(_render_section_block(section, kvs, "    "))
        out.append("")
    out.append("  };")
    out.append("}")
    return "\n".join(out) + "\n"


def render_split(doc: DconfDoc) -> dict[str, str]:
    """
    Group sections by category and render one file per category, plus a
    `default.nix` that imports all of them.

    Returns {filename: content}, including "default.nix".
    """
    buckets: dict[str, list[str]] = {}
    for section in doc.order:
        kvs = doc.sections[section]
        if not kvs:
            continue
        stem = categorize(section)
        buckets.setdefault(stem, []).append(section)

    files: dict[str, str] = {}
    for stem in sorted(buckets):
        sections = buckets[stem]
        out = [HEADER, "{ lib, ... }:", "", "{", "  dconf.settings = {"]
        for section in sections:
            out.extend(_render_section_block(section, doc.sections[section], "    "))
            out.append("")
        out.append("  };")
        out.append("}")
        files[f"{stem}.nix"] = "\n".join(out) + "\n"

    default_lines = [
        HEADER,
        "{ ... }:",
        "",
        "{",
        "  imports = [",
    ]
    for stem in sorted(buckets):
        default_lines.append(f"    ./{stem}.nix")
    default_lines.append("  ];")
    default_lines.append("}")
    files["default.nix"] = "\n".join(default_lines) + "\n"

    return files
